### PR TITLE
[RUNE]: Add categories to Rune module documentation

### LINKED ISSUE #139: [RUNE]: Split documentation's functions into categories
Currently, the rune module's functions are grouped together in one category in its documentation. It may be clearer to make use of `@category Name` in the colour functions' TSDocs to split them into a category separate from the other functions. This is an approach similar to what the CSG module is doing for its values (colours vs primitive shapes).

### PR DESCRIPTION
**Pull request by Cloud7050**
This small PR adds `@category` tags to the Rune module's variables & functions, similar to the CSG module. This helps to group them more neatly in the generated documentation, for easier reference.

Before:

image

After:

image

CSG docs:

image

Closes #139

### CODE REVIEW

**Review by lowkoklim — APPROVED** [review]

**Comment by martin-henz** [comment]
Nice!

**Comment by martin-henz** [comment]
Lots of merge conflicts: can you revisit this PR?

**Comment by Cloud7050** [comment]
> Lots of merge conflicts: can you revisit this PR?

Yes, I will do so later tonight when I get back. As #138 has now been merged into master, I will also be able to add category tags to the two new Rune functions it adds.

**Comment by Cloud7050** [comment]
image

**Pull request merged**
