### PR TITLE
[Curves] Disable slider/button for 2D render and add typedoc

### PR DESCRIPTION
**Pull request by zhenghanlee**
# Description

- Disabled slider and button upon using any 2D rendering function (e.g. `draw_points_on`) to render curves.
- Added typedoc for curves library, with examples for basic functions.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

The slider and button should be disabled upon using any 2D rendering function to render curves.

Screenshot 2021-04-13 at 11 44 45 AM

The sample code as follows:
```
import { make_point,
    make_3D_point,
    make_color_point,
    make_3D_color_point,
    draw_connected,
    draw_connected_full_view,
    draw_connected_full_view_proportional,
    draw_points_on,
    draw_points_full_view_proportional,
    draw_3D_connected,
    draw_3D_connected_full_view,
    draw_3D_connected_full_view_proportional,
    draw_3D_points_on,
    draw_3D_points_full_view_proportional,
    connect_ends,
    translate,
    scale,
    rotate_around_origin
} from "curves";

const spiral = t => make_3D_color_point(
        0.5 * math_cos(2 * math_PI * t) + 0.5,          //x-coordinate
        0.5 * math_sin(2 * math_PI * (t + 0.5)) + 0.5,  //y-coordinate
        t,                                              //z-coordinate
        math_pow(math_cos(2 * math_PI * t), 2) * 255,   //r-component
        math_pow(math_sin(2 * math_PI * t), 2) * 255,   //g-component
        t * 255);                                       //b-component
const circle = t => make_color_point(
        0.5 * math_cos(2 * math_PI * t) + 0.5,          //x-coordinate
        0.5 * math_sin(2 * math_PI * (t + 0.5)) + 0.5,  //y-coordinate
        math_pow(math_cos(2 * math_PI * t), 2) * 255,   //r-component
        math_pow(math_sin(2 * math_PI * t), 2) * 255,   //g-component
        t * 255);                                       //b-component
        
draw_points_full_view_proportional(500)(rotate_around_origin(0, math_PI/4, 0)(translate(2, 2, -2)
(scale(7, 3, 2)
(connect_ends(circle, connect_ends(spiral, circle))))));
```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by MarcusTXK** [comment]
Just a note, Source does not support trailing commas for imports, so do remember to remove the comma from the last imported item like so:
```
import { make_point,
    make_3D_point,
    make_color_point,
    make_3D_color_point,
    draw_connected,
    draw_connected_full_view,
    draw_connected_full_view_proportional,
    draw_points_on,
    draw_points_full_view_proportional,
    draw_3D_connected,
    draw_3D_connected_full_view,
    draw_3D_connected_full_view_proportional,
    draw_3D_points_on,
    draw_3D_points_full_view_proportional,
    connect_ends,
    translate,
    scale,
    rotate_around_origin
} from "curves";
```

**Comment by zhenghanlee** [comment]
> Just a note, Source does not support trailing commas for imports, so do remember to remove the comma from the last imported item like so:
> 
> ```
> import { make_point,
>     make_3D_point,
>     make_color_point,
>     make_3D_color_point,
>     draw_connected,
>     draw_connected_full_view,
>     draw_connected_full_view_proportional,
>     draw_points_on,
>     draw_points_full_view_proportional,
>     draw_3D_connected,
>     draw_3D_connected_full_view,
>     draw_3D_connected_full_view_proportional,
>     draw_3D_points_on,
>     draw_3D_points_full_view_proportional,
>     connect_ends,
>     translate,
>     scale,
>     rotate_around_origin
> } from "curves";
> ```

Oops, my bad. Updated comment.

**Comment by MarcusTXK** [comment]
Great work and good code quality. Before I approve, could you also add the following line to `scripts\docs\README.md`:
`[curves](https://source-academy.github.io/modules/documentation/modules/curves.html)`?

**Review by MarcusTXK — CHANGES_REQUESTED** [review]
Tested it and found no bugs. Great work and good code quality!

Before I approve, could you also add the following line to scripts\docs\README.md?
[curves](https://source-academy.github.io/modules/documentation/modules/curves.html)

**Comment by zhenghanlee** [comment]
> Tested it and found no bugs. Great work and good code quality!
> 
> Before I approve, could you also add the following line to `scripts\docs\README.md`?
> `[curves](https://source-academy.github.io/modules/documentation/modules/curves.html)`

Yep, added.

**Review by MarcusTXK — APPROVED** [review]
Great work!

**Pull request merged**
