### PR TITLE
Revert "Update Repository to Node 20"

### PR DESCRIPTION
**Pull request by RichDom2185**
Reverts source-academy/modules#271 due to the following error:

image

### CODE REVIEW

**Comment by leeyi45** [comment]
Oops I think I forgot that this was reliant on the PR I have open with js-slang. If that's going to take some more time I can reopen this one without that change

**Comment by RichDom2185** [comment]
Oh do you mean the [`full-async`](https://github.com/source-academy/js-slang/tree/full-async) branch? I don't see a PR open yet.

I think we have some time for now, but if people start needing to work on some modules, then we need to merge this (revert) PR so that they can test locally.

**Comment by leeyi45** [comment]
The `import-checker` branch, actually

**Review by Cloud7050 — APPROVED** [review]

**Comment by Cloud7050** [comment]
Merging as mentioned on Telegram.

**Pull request merged**
