### PR TITLE
Force game functions var args

### PR DESCRIPTION
**Pull request by gok99**
# Description

Module function var-args has been broken for awhile. Let's add a quick fix by injecting game functions `minArgsNeeded`

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Load modules and check that var args are allowed

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by lhw-1 — COMMENTED** [review]
In conjunction with [this PR](https://github.com/source-academy/frontend/pull/2664), the changes seem to have fixed the erroneous behavior for "my room". Thanks for the PR!

Will leave it to the modules team to approve & merge.

**Comment by leeyi45** [comment]
Before we go ahead with this, I do think it is worth looking into why the varargs problem exists, and what we can do to fix it for all modules without having to monkey patch things.

**Comment by gok99** [comment]
I do agree - we'll only need this by week 7, so there is some time to do something more comprehensive. 

As far as I can tell, there seems to be no good way to get information about default parameters from a Function object. So, the arity checks in js-slang will require exactly the number of required parameters to be provided:

https://github.com/source-academy/js-slang/blob/2da5bd620e4af28c6dec516335a93c69bf424ad6/src/utils/operators.ts#L108-L118

For some context, I think module varargs used to work properly (?) long ago (probably before checks of this kind were introduced with rest/spread). When things broke, it started requiring all arguments (including those with default values) - I don't have much insight as to why. It now seems like that behavior has changed and exactly the required arguments must be provided.

**Review by martin-henz — APPROVED** [review]
OK, as discussed in telegram group "SA 2425 Game".

**Pull request merged**
